### ISSUE TITLE
"command is a shell builtin"

### ISSUE THREAD

**Issue by mgodlewski** [ServiceRocket/sbt-git-flow#7]
On debian, on release I encounter this issue:

```
java.io.IOException: Cannot run program "command": error=2, Aucun fichier ou dossier de ce type
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:160)
	at sbt.AbstractProcessBuilder.getString(ProcessImpl.scala:133)
	at sbt.AbstractProcessBuilder.$bang$bang(ProcessImpl.scala:136)
	at com.servicerocket.sbt.release.git.flow.Steps$$anonfun$checkGitFlowExists$1.apply(Steps.scala:16)
	at com.servicerocket.sbt.release.git.flow.Steps$$anonfun$checkGitFlowExists$1.apply(Steps.scala:15)
```

This is du to [Steps.scala#L16](https://github.com/ServiceRocket/sbt-git-flow/blob/develop/src/main/scala/com/servicerocket/sbt/release/git/flow/Steps.scala#L16) which use "command" which is a shell builtin:

```
LANG=C type command
command is a shell builtin
```

This can be fix by using "which" instead of "command" but I don't know if this is portable.
Another way is to use 'bash -c "command "'.

A workaround is to create a fake "command" command: 
```
sudo bash -c "cat > /usr/bin/command"<<EOF
#!/bin/bash
exec which "\${@: -1}"
EOF
sudo chmod +x /usr/bin/command
```

**Comment by naderghanbari** [comment]
Thanks for pointing this out, I'm gonna look into this now.
